export const AUTORIZACIONES = {
  // USUARIOS
  CONSULTAR_USUARIOS: "PERMISO_CONSULTAR_USUARIOS",
  ELIMINAR_USUARIOS: "PERMISO_ELIMINAR_USUARIOS",
  EDITAR_USUARIOS: "PERMISO_EDITAR_USUARIOS",
  CREAR_USUARIOS: "PERMISO_CREAR_USUARIOS",

  // Mantener ambas keys para compatibilidad con codigo existente.
  CONTRASENA_USUARIOS: "PERMISO_CONTRASEÑA_USUARIOS",
  CAMBIAR_CONTRASENA: "PERMISO_CONTRASEÑA_USUARIOS",
  DESHABILITAR_USUARIOS: "PERMISO_DESHABILITAR_USUARIOS",
  HABILITAR_USUARIOS: "PERMISO_HABILITAR_USUARIOS",

  // GRUPOS
  CONSULTAR_GRUPOS: "PERMISO_CONSULTAR_GRUPOS",
  ELIMINAR_GRUPOS: "PERMISO_ELIMINAR_GRUPOS",
  EDITAR_GRUPOS: "PERMISO_EDITAR_GRUPOS",
  CREAR_GRUPOS: "PERMISO_CREAR_GRUPOS",

  // PERMISOS
  CONSULTAR_PERMISOS: "PERMISO_CONSULTAR_PERMISOS",
  ELIMINAR_PERMISOS: "PERMISO_ELIMINAR_PERMISOS",
  EDITAR_PERMISOS: "PERMISO_EDITAR_PERMISOS",
  CREAR_PERMISOS: "PERMISO_CREAR_PERMISOS",

  // MODULOS
  CONSULTAR_MODULOS: "PERMISO_CONSULTAR_MODULOS",
  ELIMINAR_MODULO: "PERMISO_ELIMINAR_MODULO",
  EDITAR_MODULO: "PERMISO_EDITAR_MODULO",
  CREAR_MODULOS: "PERMISO_CREAR_MODULOS",
  DESHABILITAR_MODULO: "PERMISO_DESHABILITAR_MODULO",
  HABILITAR_MODULO: "PERMISO_HABILITAR_MODULO",

  // SUBMODULOS
  CONSULTAR_SUBMODULOS: "PERMISO_CONSULTAR_SUBMODULOS",
  ELIMINAR_SUBMODULO: "PERMISO_ELIMINAR_SUBMODULO",
  EDITAR_SUBMODULO: "PERMISO_EDITAR_SUBMODULO",
  CREAR_SUBMODULOS: "PERMISO_CREAR_SUBMODULOS",
  DESHABILITAR_SUBMODULO: "PERMISO_DESHABILITAR_SUBMODULO",
  HABILITAR_SUBMODULO: "PERMISO_HABILITAR_SUBMODULO",

  // ACCESOS
  CONFIG_USUARIOS: "SUBMODULO_CONFIG_USUARIOS",
} as const

export type Autorizacion = (typeof AUTORIZACIONES)[keyof typeof AUTORIZACIONES]
