export const PERMISOS = {
  CAMBIAR_CONTRASENA: "PERMISO_CONTRASEÑA_USUARIOS",
  HABILITAR_USUARIOS: "PERMISO_HABILITAR_USUARIOS",
  DESHABILITAR_USUARIOS: "PERMISO_DESHABILITAR_USUARIOS",
  ELIMINAR_USUARIOS: "PERMISO_ELIMINAR_USUARIOS",
} as const

export type PermisoNombre = (typeof PERMISOS)[keyof typeof PERMISOS]
